version: "3.9"
services:
  server:
    build:
      context: .
    container_name: image_parser_bot
    command: sh -c "python main.py"
    restart: always
    env_file:
      - .env
      - .env-non-dev